export const SUBMIT_FORM_DATA = "SUBMIT_FORM_DATA";
export const SUBMIT_FORM_DATA_SUCCESS = "SUBMIT_FORM_DATA_SUCCESS";
export const SUBMIT_FORM_DATA_ERROR = "SUBMIT_FORM_DATA_ERROR";
export const SUBMIT_FORM_DATA_RESET = "SUBMIT_FORM_DATA_RESET";